### ISSUE TITLE
[TypeError: Cannot read property 'startSpeech' of null]

### ISSUE THREAD

**Issue by CoderLzz** [react-native-voice/voice#568]
"react-native": "0.76.9", gradle-8.10.2-all.zip, Error reported when calling the Voice.start ('zh CN ') method：[TypeError: Cannot read property 'startSpeech' of null]

**Comment by mmehul** [comment]
same here. I was facing same issue on Android only. iOS device working.

**Comment by amar557** [comment]
Any alternate of this package

**Comment by ObaidHere** [comment]
> > try this @appcitor/react-native-voice-to-text work for me on both iOS and android, react native 0.80
> 
> Hi, thanks this works, but seems it listens only for a single time, and closes the listner Like the listner dosent stay up to receive further text. it stops after receiving the first text
> 
> I don't know, if i am the only one having this issue, because am using this for a bot, and i have to continually receive text, so the listener has to stay open
> 
> [@ObaidHere](https://github.com/ObaidHere)

am using it as a global listner only remove then app is closed or moves to background it perfectly working for me.

**Comment by pratham-srivastava-07** [comment]
HI i am using this but when i start the recording i get _reactNativeVoiceToText.default.start is not a function (it is undefined).

Any solution would be much appreciated.


> > > try this @appcitor/react-native-voice-to-text work for me on both iOS and android, react native 0.80
> > 
> > 
> > it is not working with "react": "19.0.0", "react-native": "0.78.1", "react-native-voice-to-text": "^0.1.4"
> 
> try "@appcitor/react-native-voice-to-text": "^0.2.1"

**Comment by amar557** [comment]
> no one maintains this repo anymore
> 
> why not use https://github.com/jamsch/expo-speech-recognition ?

because we can not use it in RN cli

**Comment by anon1911** [comment]
> > no one maintains this repo anymore
> > why not use https://github.com/jamsch/expo-speech-recognition ?
> 
> because we can not use it in RN cli

afaik it's another module system (same with nitro) ;; it shouldn't matter if you use RN cli as long as you add the native code for autolinking the native expo modules

https://docs.expo.dev/bare/installing-expo-modules/

**Comment by rahulnainwalttn** [comment]
Is it working on iOS? I am using this version, and it is not working in iOS.

`"@react-native-voice/voice": "npm:yet-another-react-native-voice@4.0.0"`

**Comment by safaiyeh** [comment]
This project has been deprecated and archived. Please migrate to [`expo-speech-recognition`](https://github.com/jamsch/expo-speech-recognition).
Thank you for your contributions! ❤️
